# rutas.yml
---
root_route:
    path:     /
    controller: 'homePageFunction'
    methods:   [ GET ]

user_list_route:
    path:     /users
    controller: 'listUsersFunction'
    methods:
        - GET

user_route:
    path:     /users/{name}
    controller: 'userFunction'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE