# rutas.yml
---
root_route:
    path:     /
    controller: 'homePageFunction'
    methods:   [ GET ]

user_list_route:
    path:     /users
    controller: 'listUsersFunction'
    methods:
        - GET

user_create_route:
    path: /users/create
    controller: 'createUserFunction'
    methods: [ GET, POST ]

user_route:
    path:     /users/{name}
    controller: 'userFunction'
    defaults:
        name: _default_
    methods:
        - GET


user_update_route:
    path: /users/update/{id}
    controller: 'updateUserFunction'
    methods: [ GET, POST ]

user_delete_route:
    path: /users/delete/{id}
    controller: 'deleteUserFunction'
    methods: [ DELETE, POST ]